# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57cd3899696e5038743277727ed585a6"
name = "ReceipTap test 2"
application_url = "https://www.receiptap.com"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://www.receiptap.com/oauth/shopify/callback" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://www.receiptap.com/webhooks/pos/shopify/compliance"
