-- AlterTable
ALTER TABLE "ReceiptTheme" ADD COLUMN     "barcodeValue" TEXT NOT NULL DEFAULT 'receiptNumber',
ADD COLUMN     "customLinkLabel" TEXT,
ADD COLUMN     "customLinkUrl" TEXT,
ADD COLUMN     "footerLegal" TEXT,
ADD COLUMN     "itemLayout" TEXT NOT NULL DEFAULT 'compact',
ADD COLUMN     "offerLine" TEXT,
ADD COLUMN     "promoButtonLabel" TEXT,
ADD COLUMN     "promoButtonUrl" TEXT,
ADD COLUMN     "promoExpiryText" TEXT,
ADD COLUMN     "promoMessage" TEXT,
ADD COLUMN     "promoTitle" TEXT,
ADD COLUMN     "showBarcode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showDateTime" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showDiscounts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showItemLineTotal" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showItemQuantity" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showItemUnitPrice" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showPaymentMethod" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showPromo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showReceiptNumber" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showRegister" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showSubtotal" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showTax" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showTotal" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "socialsHeading" TEXT,
ADD COLUMN     "totalProminent" BOOLEAN NOT NULL DEFAULT true;
